database_address = "192.168.0.4"
database_user = "root"
database_password = "root"
database_port = 3306
database_name = "cms-and-go"
webserver_port = 8080
admin_port = 8081
image_dir = "./images"
cache_enabled = true

[navbar]
links = [
    { name = "Home", href = "/", title = "Homepage" },
    { name = "About", href = "/about", title = "About page" },
    { name = "Services", href = "/services", title = "Services page" },
    { name = "Images", href = "/images", title = "Images page" },
    { name = "Contact", href = "/contact", title = "Contacts page" },
]

[navbar.dropdowns]
Gallery = [
    { name = "Lindos", href = "/gallery/lindos", title = "Lindos" },
    { name = "Rhodes", href = "/gallery/rhodes", title = "Rhodes" },
]

# Gallery Settings
# Paths should be relative to the image directory!
[gallery.lindos]
name = "Lindos"
description = "Pictures taken in our visits to Lindos"
link = "lindos"
thumbnail = "images/data/5c320138-5acb-487b-b008-afecc2ab6ac4.jpg"
images = [
    "5c320138-5acb-487b-b008-afecc2ab6ac4.json",
    "8c1a34cf-ffae-423f-8a04-d036154a8ac5.json",
    "74f82e0a-d406-4ff9-959a-5d5e4dbf81bb.json",
    "387cf2cd-5534-48ed-8a14-a6ad9b171faf.json",
    "818dc59f-5138-42f4-b0f8-cca2e019b940.json",
    "abc2ced4-2858-496f-adae-8e61d7f82ef9.json",
    "bec1275b-fab7-4982-a0fd-7839db2bb6eb.json",
    "c9072802-bab6-4fe5-80d6-c41a7465cd0e.json",
    "e707c4a0-909e-4952-a5ac-cde8ab8d262a.json",
    "e67004ec-4c44-4676-bc06-2c5caab56470.json",
    "fda98db9-d827-4788-af85-aa20e68d2f51.json",
]

[gallery.rhodes]
name = "Rhodes"
description = "Pictures taken in our visits to Rhodes"
link = "rhodes"
thumbnail = "images/data/5c320138-5acb-487b-b008-afecc2ab6ac4.jpg"
images = [
    "5c320138-5acb-487b-b008-afecc2ab6ac4.json",
    "8c1a34cf-ffae-423f-8a04-d036154a8ac5.json",
    "74f82e0a-d406-4ff9-959a-5d5e4dbf81bb.json",
    "387cf2cd-5534-48ed-8a14-a6ad9b171faf.json",
    "818dc59f-5138-42f4-b0f8-cca2e019b940.json",
    "abc2ced4-2858-496f-adae-8e61d7f82ef9.json",
    "bec1275b-fab7-4982-a0fd-7839db2bb6eb.json",
    "c9072802-bab6-4fe5-80d6-c41a7465cd0e.json",
    "e707c4a0-909e-4952-a5ac-cde8ab8d262a.json",
    "e67004ec-4c44-4676-bc06-2c5caab56470.json",
    "fda98db9-d827-4788-af85-aa20e68d2f51.json",
]


[[shortcodes]]
name = "img"
plugin = "plugins/image_shortcode.lua"

[[shortcodes]]
name = "table"
plugin = "plugins/table_shortcode.lua"
