version: '3.8'

services:
  golang_app:
    image: andrenormanlang/cms-golang:01
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: .
        target: /gocms
        volume:
          nocopy: true
    working_dir: /gocms
    command: ./compose-run.sh
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always
    networks:
      - common-net

  golang_admin_app:
    image: andrenormanlang/cms-golang:01
    ports:
      - "8081:8081"
    volumes:
      - type: bind
        source: .
        target: /gocms
        volume:
          nocopy: true
    working_dir: /gocms
    command: ./compose-admin-run.sh
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - PORT=8081
    restart: always
    networks:
      - common-net

  mariadb:
    image: mariadb:11.2.3-jammy
    container_name: mariadb
    env_file:
      - ./.dev.env
    healthcheck:
      test: [ "CMD", "mariadb", "-u", "root", "-proot", "-e", "USE cms-and-go" ]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - common-net

networks:
  common-net: {}
