services:
  cmsgo_app:
    container_name: cmsgo_app
    image: ${CMSGO_APP_CONTAINER}
    ports:
      - "8080:8080"
    command:
      - /bin/sh
      - -c
      - |
        cd /app/migrations && GOOSE_DRIVER="mysql" GOOSE_DBSTRING="cmsgo:cmsgopw@tcp(mariadb:3306)/cms-and-go" goose reset
        GOOSE_DRIVER="mysql" GOOSE_DBSTRING="cmsgo:cmsgopw@tcp(mariadb:3306)/cms-and-go" goose up
        cd /app && ./gocms --config ./cmsgo_config.toml
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider http://localhost:8080/health", "||", "exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      PATH: "/root/go/bin:/usr/local/bin:/usr/bin:/sbin:$PATH"
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always
    networks:
      - common-net
      - cmsgo-network

  mariadb:
    image: mariadb:11.2.3-jammy
    container_name: mariadb
    environment:
      MARIADB_ADDRESS: localhost
      MARIADB_PORT: 3306
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: cms-and-go
      MARIADB_USER: cmsgo
      MARIADB_PASSWORD: cmsgopw
    healthcheck:
      test: [ "CMD", "mariadb", "-u", "root", "-proot", "-e", "USE cms-and-go" ]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - common-net

networks:
  common-net: {}
  urchin-network:
    external: true