services:
  golang_admin_app:
    container_name: cmsgo_admin_app
    image: andrenormanlang/cms-golang:0.3
    ports:
      - "8081:8081"
    volumes:
      - type: bind
        source: ${GITHUB_WORKSPACE:-..}
        target: /gocms
        bind:
          create_host_path: true
    command: /gocms/docker/start-admin-app.sh
    healthcheck:
      test: [ "CMD", "sh", "-c", "wget --no-verbose --tries=1 --spider http://localhost:8081/health || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 10
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always
    networks:
      - common-net
  golang_app:
    container_name: cmsgo_app
    image: andrenormanlang/cms-golang:0.3
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ${GITHUB_WORKSPACE:-..}
        target: /gocms
        bind:
          create_host_path: true
    command: /gocms/docker/start-app.sh
    healthcheck:
      test: [ "CMD", "sh", "-c", "wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 10
    depends_on:
      mariadb:
        condition: service_healthy
      golang_admin_app:
        condition: service_healthy
    restart: always
    networks:
      - common-net

  mariadb:
    image: mariadb:11.2.3-jammy
    container_name: mariadb
    ports:
      - "3306:3306"
    env_file:
      - ../.dev.env
    environment:
      MARIADB_ADDRESS: localhost
      MARIADB_PORT: 3306
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: cms-and-go
      MARIADB_USER: cmsgo
      MARIADB_PASSWORD: cmsgopw
    healthcheck:
      test: [ "CMD", "mariadb", "-u", "root", "-proot", "-e", "USE cms-and-go" ]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - common-net

networks:
  common-net: {}
