include:
  - docker-compose.yml

services:

  timer:
    image: alpine
    command: sh -c "sleep 20 && echo 'Timer finished'"
    depends_on:
      mariadb:
        condition: service_healthy
      golang_admin_app:
        condition: service_healthy
      golang_app:
        condition: service_healthy