name: golangci-lint step
description: Runs golangci-lint with specified linters

inputs:
  linters:
    description: "One or more linter names separated by semicolons (e.g. errcheck;staticcheck;unused)."
    required: true

runs:
  using: composite
  steps:
    - name: Generating templ files
      run: |
        templ generate
      shell: bash

    - name: Prepare linter command
      id: set-command
      run: |
        export LINTERS="${{ inputs.linters }}"
        # Turn semicolon-separated linters into multiple -E flags
        export LINTER_CMD="golangci-lint run --timeout 2m --disable-all -E ${LINTERS//;/ -E }"
        echo "linter_cmd=${LINTER_CMD}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Run the linter
      run: eval ${{ steps.set-command.outputs.linter_cmd }}
      shell: bash
